#!/bin/bash

###############################################################################
# IT-Grads Deployment Script
# Деплой клиента и сервера на https://itgrads.ru/
###############################################################################

set -e  # Exit on any error

# Load deployment variables
source .deployment-vars

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║        IT-Grads Deployment to itgrads.ru                  ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Function to print colored messages
print_status() {
    echo -e "${GREEN}✓${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_info() {
    echo -e "${YELLOW}ℹ${NC} $1"
}

# Check SSH connections
print_info "Checking server connections..."

if ! ssh -o ConnectTimeout=5 "${SERVER_USER}@${APP_SERVER_IP}" "echo 'App Server OK'" > /dev/null 2>&1; then
    print_error "Cannot connect to App Server (${APP_SERVER_IP})"
    exit 1
fi
print_status "App Server connection OK"

if ! ssh -o ConnectTimeout=5 "${SERVER_USER}@${DB_SERVER_IP}" "echo 'DB Server OK'" > /dev/null 2>&1; then
    print_error "Cannot connect to DB Server (${DB_SERVER_IP})"
    exit 1
fi
print_status "DB Server connection OK"

# Ask for database password
echo ""
print_info "Please enter the database password for user '${DB_USER}':"
read -s DB_PASSWORD
echo ""

# Build frontend
print_info "Building frontend..."
cd "${LOCAL_FRONTEND_PATH}"
npm install
npm run build
print_status "Frontend built successfully"

# Build backend (if needed)
print_info "Preparing backend..."
cd "../../${LOCAL_BACKEND_PATH}"
npm install --production
print_status "Backend dependencies installed"

# Create necessary directories on App Server
print_info "Setting up directories on App Server..."
ssh "${SERVER_USER}@${APP_SERVER_IP}" << EOF
    mkdir -p ${SERVER_PATH}
    mkdir -p ${SERVER_BACKEND_PATH}
    mkdir -p ${SERVER_FRONTEND_PATH}
EOF
print_status "Directories created"

# Deploy Backend
print_info "Deploying backend to ${APP_SERVER_IP}..."
rsync -avz --delete \
    --exclude 'node_modules' \
    --exclude '.git' \
    --exclude '.env*' \
    --exclude '*.log' \
    "../../${LOCAL_BACKEND_PATH}/" \
    "${SERVER_USER}@${APP_SERVER_IP}:${SERVER_BACKEND_PATH}/"

# Create .env.production on server
print_info "Creating production environment file..."
ssh "${SERVER_USER}@${APP_SERVER_IP}" << EOF
    cat > ${SERVER_BACKEND_PATH}/.env.production << 'ENVEOF'
NODE_ENV=production
PORT=5001
DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_SERVER_IP}:5432/${DB_NAME}
JWT_SECRET=\${JWT_SECRET:-super_secret_access_key}
JWT_REFRESH_SECRET=\${JWT_REFRESH_SECRET:-super_secret_refresh_key}
JWT_ACCESS_EXPIRES=15m
JWT_REFRESH_EXPIRES=7d
ENVEOF
EOF

print_status "Backend deployed"

# Deploy Frontend
print_info "Deploying frontend to ${APP_SERVER_IP}..."
rsync -avz --delete \
    "../../${LOCAL_FRONTEND_PATH}/dist/" \
    "${SERVER_USER}@${APP_SERVER_IP}:${SERVER_FRONTEND_PATH}/"
print_status "Frontend deployed"

# Install backend dependencies on server
print_info "Installing backend dependencies on server..."
ssh "${SERVER_USER}@${APP_SERVER_IP}" << EOF
    cd ${SERVER_BACKEND_PATH}
    npm install --production
EOF
print_status "Dependencies installed"

# Setup PM2 for backend
print_info "Setting up PM2 process manager..."
ssh "${SERVER_USER}@${APP_SERVER_IP}" << 'EOF'
    # Install PM2 globally if not exists
    if ! command -v pm2 &> /dev/null; then
        npm install -g pm2
    fi

    cd ${SERVER_BACKEND_PATH}

    # Stop existing process
    pm2 stop ${PM2_APP_NAME} || true
    pm2 delete ${PM2_APP_NAME} || true

    # Start new process
    pm2 start server.js \
        --name ${PM2_APP_NAME} \
        --env production \
        --max-memory-restart 500M \
        --time

    # Save PM2 configuration
    pm2 save

    # Setup PM2 startup script
    pm2 startup systemd -u ${SERVER_USER} --hp /root || true
EOF
print_status "PM2 configured"

# Setup Nginx
print_info "Configuring Nginx..."
ssh "${SERVER_USER}@${APP_SERVER_IP}" << 'EOF'
    # Install Nginx if not exists
    if ! command -v nginx &> /dev/null; then
        apt-get update
        apt-get install -y nginx
    fi

    # Create Nginx configuration
    cat > /etc/nginx/sites-available/itgrads << 'NGINXEOF'
# Redirect HTTP to HTTPS
server {
    listen 80;
    server_name itgrads.ru www.itgrads.ru;

    # Let's Encrypt verification
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$server_name$request_uri;
    }
}

# HTTPS configuration
server {
    listen 443 ssl http2;
    server_name itgrads.ru www.itgrads.ru;

    # SSL certificates (will be generated by Certbot)
    ssl_certificate /etc/letsencrypt/live/itgrads.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/itgrads.ru/privkey.pem;

    # SSL settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Frontend - serve static files
    location / {
        root ${SERVER_FRONTEND_PATH};
        try_files \$uri \$uri/ /index.html;

        # Cache static assets
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
    }

    # Backend API
    location /api/ {
        proxy_pass http://localhost:5001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
    }

    # Additional API routes
    location ~ ^/(auth|user|cookies)/ {
        proxy_pass http://localhost:5001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
    }

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;

    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml+rss application/javascript application/json;
}
NGINXEOF

    # Enable site
    ln -sf /etc/nginx/sites-available/itgrads /etc/nginx/sites-enabled/

    # Remove default site if exists
    rm -f /etc/nginx/sites-enabled/default

    # Test Nginx configuration
    nginx -t

    # Reload Nginx
    systemctl reload nginx
    systemctl enable nginx
EOF
print_status "Nginx configured"

# Setup SSL with Let's Encrypt
print_info "Setting up SSL certificates with Let's Encrypt..."
ssh "${SERVER_USER}@${APP_SERVER_IP}" << 'EOF'
    # Install Certbot if not exists
    if ! command -v certbot &> /dev/null; then
        apt-get update
        apt-get install -y certbot python3-certbot-nginx
    fi

    # Create directory for Let's Encrypt verification
    mkdir -p /var/www/certbot

    # Get SSL certificate
    certbot --nginx -d itgrads.ru -d www.itgrads.ru --non-interactive --agree-tos --email admin@itgrads.ru --redirect

    # Setup auto-renewal
    systemctl enable certbot.timer
    systemctl start certbot.timer
EOF
print_status "SSL certificates configured"

# Sync database
print_info "Synchronizing database schema..."
ssh "${SERVER_USER}@${APP_SERVER_IP}" << 'EOF'
    cd ${SERVER_BACKEND_PATH}
    NODE_ENV=production npm run db:sync
EOF
print_status "Database synchronized"

# Restart backend
print_info "Restarting backend..."
ssh "${SERVER_USER}@${APP_SERVER_IP}" "pm2 restart ${PM2_APP_NAME}"
print_status "Backend restarted"

# Check deployment status
print_info "Checking deployment status..."
sleep 3

ssh "${SERVER_USER}@${APP_SERVER_IP}" << EOF
    echo "PM2 Status:"
    pm2 status
    echo ""
    echo "Backend logs (last 10 lines):"
    pm2 logs ${PM2_APP_NAME} --lines 10 --nostream
EOF

echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║              Deployment Completed Successfully!           ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""
print_status "Frontend: https://itgrads.ru"
print_status "Backend API: https://itgrads.ru/api"
print_status "App Server: ${APP_SERVER_IP}"
print_status "DB Server: ${DB_SERVER_IP}"
echo ""
print_info "Next steps:"
echo "  1. Visit https://itgrads.ru to verify the deployment"
echo "  2. Check backend health: curl -Ik https://itgrads.ru/api"
echo "  3. Monitor logs: ssh ${SERVER_USER}@${APP_SERVER_IP} 'pm2 logs ${PM2_APP_NAME}'"
echo ""
